site_name: Microsoft Biodiversity
site_url: https://microsoft.github.io/Biodiversity/
site_description: "Microsoft AI for Good Lab Biodiversity hub: open-source conservation AI for wildlife monitoring. Home of MegaDetector, PyTorch-Wildlife, SPARROW, and MegaDetector-Acoustic."
docs_dir: docs
site_dir: site
repo_url: https://github.com/microsoft/Biodiversity
repo_name: microsoft/Biodiversity
copyright: Copyright (c) 2023 Microsoft Corporation

theme:
  name: material
  custom_dir: overrides
  favicon: assets/cat.png
  logo: assets/cat.png
  icon:
    menu: material/menu
    alternate: material/translate
    search: material/magnify
    share: material/share-variant
    close: material/close
    top: material/arrow-up
    edit: material/pencil
    view: material/eye
    repo: fontawesome/brands/git-alt
    admonition:
      note: material/note
      abstract: material/lightbulb
      info: material/information
      tip: material/lightbulb-on
      success: material/check-circle
      question: material/help-circle
      warning: material/alert
      failure: material/alert-circle
      danger: material/alert-octagon
      bug: material/bug
      example: material/format-list-bulleted
      quote: material/format-quote-open
    tag:
      default: material/tag
      info: material/information
      warning: material/alert
      danger: material/alert-octagon
    previous: material/arrow-left
    next: material/arrow-right
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: green
      accent: deep orange
      toggle:
        icon: material/paw-off
        name: Switch to dark mode
        
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: deep orange
      toggle:
        icon: material/paw
        name: Switch to light mode
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - toc.follow
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.share
    - navigation.footer

nav:
  - Microsoft Biodiversity:
    - Overview: index.md
    - The Ecosystem: ecosystem.md
    - Core Features: core_features.md
    - MegaDetector: megadetector.md
    - MegaDetector-Acoustic: bioacoustics.md
    - Installation: installation.md
    - Tags: tags.md
    - Existing Collaborators: collaborators.md
    - Contributors: contributors.md
    - Cite Us: cite.md
  - What's New?:
    - Latest Release: releases/release_notes.md
    - Past Releases: releases/past_releases.md
    - PW-Engine Preview: pw_engine_overview.md
  - Model Zoo:
    - MegaDetector: model_zoo/megadetector.md
    - Other Detectors: model_zoo/other_detectors.md
    - Classifiers: model_zoo/classifiers.md
    - Bioacoustics: model_zoo/bioacoustics.md
  - Demo and UI:
    - Demo Data: demo_and_ui/demo_data.md
    - Notebook: demo_and_ui/notebook.md
    - Gradio App: demo_and_ui/gradio.md
    - AddaxAI (formerly known as EcoAssist): demo_and_ui/ecoassist.md
    - TimeLapse: demo_and_ui/timelapse.md
    - BoquilaHUB: demo_and_ui/boquilahub.md
  - Contribute:
    - Contribute Guidelines: contribute.md
    - Documentation Standards: ecosystem-standards.md
    - License: license.md
    - Developer Guide: build_mkdocs.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - attr_list
  - sane_lists
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true


plugins:
  - callouts
  - search
  - meta
  - tags
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
      fallback_to_build_date: true
  - redirects:
      redirect_maps:
        'base/data/datasets.md': 'https://microsoft.github.io/Pytorch-Wildlife/base/data/datasets/'
        'base/data/transforms.md': 'https://microsoft.github.io/Pytorch-Wildlife/base/data/transforms/'
        'base/models/classification/base_classifier.md': 'https://microsoft.github.io/Pytorch-Wildlife/base/models/classification/base_classifier/'
        'base/models/classification/resnet_base/amazon.md': 'https://microsoft.github.io/Pytorch-Wildlife/base/models/classification/resnet_base/amazon/'
        'base/models/classification/resnet_base/base_classifier.md': 'https://microsoft.github.io/Pytorch-Wildlife/base/models/classification/resnet_base/base_classifier/'
        'base/models/classification/resnet_base/custom_weights.md': 'https://microsoft.github.io/Pytorch-Wildlife/base/models/classification/resnet_base/custom_weights/'
        'base/models/classification/resnet_base/opossum.md': 'https://microsoft.github.io/Pytorch-Wildlife/base/models/classification/resnet_base/opossum/'
        'base/models/classification/resnet_base/serengeti.md': 'https://microsoft.github.io/Pytorch-Wildlife/base/models/classification/resnet_base/serengeti/'
        'base/models/classification/timm_base/DFNE.md': 'https://microsoft.github.io/Pytorch-Wildlife/base/models/classification/timm_base/DFNE/'
        'base/models/classification/timm_base/Deepfaune.md': 'https://microsoft.github.io/Pytorch-Wildlife/base/models/classification/timm_base/Deepfaune/'
        'base/models/classification/timm_base/base_classifier.md': 'https://microsoft.github.io/Pytorch-Wildlife/base/models/classification/timm_base/base_classifier/'
        'base/models/detection/base_detector.md': 'https://microsoft.github.io/Pytorch-Wildlife/base/models/detection/base_detector/'
        'base/models/detection/herdnet.md': 'https://microsoft.github.io/Pytorch-Wildlife/base/models/detection/herdnet/'
        'base/models/detection/herdnet/animaloc/data/patches.md': 'https://microsoft.github.io/Pytorch-Wildlife/base/models/detection/herdnet/animaloc/data/patches/'
        'base/models/detection/herdnet/animaloc/data/types.md': 'https://microsoft.github.io/Pytorch-Wildlife/base/models/detection/herdnet/animaloc/data/types/'
        'base/models/detection/herdnet/animaloc/eval/lmds.md': 'https://microsoft.github.io/Pytorch-Wildlife/base/models/detection/herdnet/animaloc/eval/lmds/'
        'base/models/detection/herdnet/animaloc/eval/stitchers.md': 'https://microsoft.github.io/Pytorch-Wildlife/base/models/detection/herdnet/animaloc/eval/stitchers/'
        'base/models/detection/herdnet/dla.md': 'https://microsoft.github.io/Pytorch-Wildlife/base/models/detection/herdnet/dla/'
        'base/models/detection/herdnet/model.md': 'https://microsoft.github.io/Pytorch-Wildlife/base/models/detection/herdnet/model/'
        'base/models/detection/ultralytics_based/Deepfaune.md': 'https://microsoft.github.io/Pytorch-Wildlife/base/models/detection/ultralytics_based/Deepfaune/'
        'base/models/detection/ultralytics_based/megadetectorv5.md': 'https://microsoft.github.io/Pytorch-Wildlife/base/models/detection/ultralytics_based/megadetectorv5/'
        'base/models/detection/ultralytics_based/megadetectorv6.md': 'https://microsoft.github.io/Pytorch-Wildlife/base/models/detection/ultralytics_based/megadetectorv6/'
        'base/models/detection/ultralytics_based/megadetectorv6_distributed.md': 'https://microsoft.github.io/Pytorch-Wildlife/base/models/detection/ultralytics_based/megadetectorv6_distributed/'
        'base/models/detection/ultralytics_based/yolov5_base.md': 'https://microsoft.github.io/Pytorch-Wildlife/base/models/detection/ultralytics_based/yolov5_base/'
        'base/models/detection/ultralytics_based/yolov8_base.md': 'https://microsoft.github.io/Pytorch-Wildlife/base/models/detection/ultralytics_based/yolov8_base/'
        'base/models/detection/ultralytics_based/yolov8_distributed.md': 'https://microsoft.github.io/Pytorch-Wildlife/base/models/detection/ultralytics_based/yolov8_distributed/'
        'base/overview.md': 'https://microsoft.github.io/Pytorch-Wildlife/base/overview/'
        'base/utils/misc.md': 'https://microsoft.github.io/Pytorch-Wildlife/base/utils/misc/'
        'base/utils/post_process.md': 'https://microsoft.github.io/Pytorch-Wildlife/base/utils/post_process/'
        'fine_tuning_modules/classification/overview.md': 'https://microsoft.github.io/Pytorch-Wildlife/fine_tuning_modules/classification/overview/'
        'fine_tuning_modules/detection/overview.md': 'https://microsoft.github.io/Pytorch-Wildlife/fine_tuning_modules/detection/overview/'
        'fine_tuning_modules/overview.md': 'https://microsoft.github.io/Pytorch-Wildlife/fine_tuning_modules/overview/'